version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
    ports:
      - "3306:3306"
    volumes:
      - ./src/test/sql/:/docker-entrypoint-initdb.d/
