package sample.domain.model;

import java.util.List;

public class Parent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.name
     *
     * @mbg.generated
     */
    private String name;


    private List<Child> children;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.id
     *
     * @return the value of parent.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.id
     *
     * @param id the value for parent.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.age
     *
     * @return the value of parent.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.age
     *
     * @param age the value for parent.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.name
     *
     * @return the value of parent.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.name
     *
     * @param name the value for parent.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    public List<Child> getChildren() {
        return children;
    }

    public void setChildren(List<Child> children) {
        this.children = children;
    }
}